steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --dockerfile=Dockerfile
      - --destination=europe-west1-docker.pkg.dev/kringloop2/bas-frontend/frontend-image:latest
      - --cache=false
      - --cache-ttl=72h
options:
  logging: CLOUD_LOGGING_ONLY